image: node:16

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build    # Build the TypeScript project
    # - npm run migrate
  artifacts:
    paths:
      - dist            # Save the build directory for deployment

deploy_to_heroku:
  stage: deploy
  script:
    - curl https://cli-assets.heroku.com/install.sh | sh  # Install Heroku CLI
    - echo "$HEROKU_API_KEY" | heroku auth:token         # Authenticate Heroku
    - heroku git:remote -a updish-staging                 # Replace with your Heroku app name
    - git push heroku HEAD:main                          # Push to Heroku
  only:
    - main                                               # Deploy only from the main branch
